### ISSUE TITLE
What to do with previously-contributed work under pseudonyms?

### ISSUE THREAD

**Issue by domenic** [whatwg/sg#101]
Related to #93, but deserves its own issue.

It appears the editors have (per the current direction of #93) erroneously "verified" several individuals despite them likely using pseudonyms:

- https://github.com/whatwg/participant-data/commit/f72a2236a222ee61af997e49208a14d498b1e70b @Yay295: [commits](https://github.com/search?q=author%3AYay295+org%3Awhatwg)
- https://github.com/whatwg/participant-data/commit/39fbf479ff6aa4165f6baeae36b5363ec9f36ca9 @payingattention: [commits](https://github.com/search?q=author%3Apayingattention+org%3Awhatwg)
- https://github.com/whatwg/participant-data/commit/d89eb561515915d11eef02fae8e4c0fd941636d8 @Rondinelly (edit: fixed!)
- https://github.com/whatwg/participant-data/commit/4b1bac6e2ee53d57f54258747de28b66d9f9c117 @Osintopsec: [commits](https://github.com/search?q=author%3AOsintopsec+org%3Awhatwg)

To the mentioned individuals, would you be able to send a pull request correcting https://github.com/whatwg/participant-data/blob/master/individuals.json to contain the name you usually use to sign contracts?

In cases where that's not possible, would the SG suggest reverting those commits?

**Comment by othermaciej** [comment]
It would probably be correct to unverified those individuals.

**Comment by domenic** [comment]
I've updated the OP with links to the commits in question. None are normative. The most-substantial is https://github.com/whatwg/fetch/commit/d219389264742ce9bb3411601f680f54a77e2f3a which updates an example that was contradicting the normative standard to be in line with the standard.

**Comment by annevk** [comment]
Note also that in most of these cases editors would have to make identical commits. https://github.com/whatwg/fetch/commit/c9fa1fc68248d031e9937f79754e690a0a8909c1 is a related example where I could not accept a PR for IPR reasons, but fixing the mistake it highlighted wasn't really possible in any other way than the PR presented. Not being able to merge the original PR in those cases comes across rather petty.

**Comment by payingattention** [comment]
> whatwg/participant-data@39fbf47 @payingattention: commits

> To the mentioned individuals, would you be able to send a pull request correcting https://github.com/whatwg/participant-data/blob/master/individuals.json to contain the name you usually use to sign contracts?

I used my real name. Why suddenly now (did W3.org/whatwg.org require you do any due diligence, a single official search?), I am being asked to reverify my name (again...)?

My legal name change paperwork can be verified with http://publicnotices.thedailyrecord.com/search/detail.aspx?detail=11032729 (https://web.archive.org/web/20170511150040/http://publicnotices.thedailyrecord.com/search/detail.aspx?detail=11032729, https://archive.vn/wip/DquhP, https://conifer.rhizome.org/037/identity-accounts/20200718121732/https://publicnotices.thedailyrecord.com/search/detail.aspx?detail=11032729).

I mean I understand that to get my Stimulus Check (EIP payment) even the IRS.gov has me doing https://en.wikipedia.org/wiki/Phone_tag with the SSA.gov pretending like they're not able to use computers to store and track my paper work, I've been put on waiting 37 minutes "on hold" (should be a "Use of Force" term if used like that, put in a cyberhold, a cyberbrig...) every time I call, and they're still telling me (half the time, half can somehow, maybe they're using the legacy Oracle.com version with an actual living breathing shamantic oracle, because it seems to be a personal decision if to read my ID as valid) they're not able to verify my name that was verified with a red stamp and gold seal (for several hundred $dollars, in addition to my verifying with LegalZoom.com as explained partially in https://www.facebook.com/notes/prosody-vereable-context/why-ur-name-makes-sense-because-gov-name-makes-feel-gag-orders-talk-hurt/10152911445569178/ in 2015 before Facebook.com "flagged" (is not a legal terminology, is hexspeak/hackerspeak prime, "flag" means A Human Not Named Responsible Officially Did That) my account [Facebook.com/prosody](https://facebook.com/prosody)) at the main Baltimore, Maryland courthouse by a U.S. court judge.

Why am I being asked to verify my name when I have sent my real ID to every major social media network organization and really verified my identity to a greater degree offiicial than many people with red carpet marked "Official"/"Verified" accounts.

I am being attacked for "decentralizing" when "central" agencies can not verify me a single individual with deep public accounts going back 20 years, me 99% of the time with a single IP address, me writing cleartext in clearnet 99% of the time? There are leaders and CEO's (many who use PGP over Git Support Issue Tickets) who do not have as much identity paperwork proof/verification/evidence as I voluntarily prove for the record.

My name change reason was officially on paper "My username is my name of common usage.", also for the record, I wish the entire identity proof was made public record, maybe through https://my.key.gov (sp https://my.id.gov?).

I can verify with my government id paperwork, I can post here, I can use an identity verification service, and you can ask https://www.quora.com/profile/Prosody-Vereable-Context/questions the Quora.com superadmins who changed my name (even though I can not edit because they've got me cyberbrigged) after I gave my gov id, all have my same gov't identity paperwork.

I can verify by video with https://YouTube.com/iGabe, I can also verify my all my keys with https://keybase.io/memorization, I can make a post with a keyword you specify to verify I wrote here in 137 ways.

<sup>P.S. Yo/hello @annevk, it is not personal, I am talking about the process not the individuals (even though I am talking about me as an individual), the `process` is important, please do not take personally.</sup>

**Comment by foolip** [comment]
The SG talked about this yesterday, see https://github.com/whatwg/sg/issues/137.

While the current answer to "[Can contributors use pseudonyms to sign the participation agreement?](https://github.com/whatwg/sg/issues/93)" is "no", we do _not_ recommend the contributions that have already happened. That would not be productive, especially as the changes are quite small per @domenic's checking in https://github.com/whatwg/sg/issues/101#issuecomment-659496711.

Our recommended resolution is to unverify @Yay295 and @Osintopsec.

@Rondinelly fixed their name in https://github.com/whatwg/participant-data/pull/15, and @payingattention stated in this thread that they're not using a pseudonym. @payingattention, can you confirm that it should be "Prosody Vereable Context(", or is it actually "Prosody Vereable Context" or "Prosody Vereable Context (Gabriel Gaston Croft)"? Apologies for the trouble, and thanks for contributing to the WHATWG!

This does not resolve the issue of what exactly editors should do when verifying an individual, but I'll file a separate issue for that.

**Comment by foolip** [comment]
I've sent https://github.com/whatwg/participant-data/pull/27 to unverify @Yay295 and @Osintopsec. For both of you, if you are following this thread and would like to contribute to the WHATWG going forward, please do speak up or reach out in email to sg@whatwg.org if you'd prefer. What will happen if https://github.com/whatwg/participant-data/pull/27 is merged is that future attempts to contribute to a WHATWG Living Standard will require verification. Perhaps by then we will have resolved https://github.com/whatwg/sg/issues/93, but I can't make any promises.

**Comment by foolip** [comment]
I've filed https://github.com/whatwg/sg/issues/138 for the remaining issue here.

**Comment by payingattention** [comment]
> and @payingattention stated in this thread that they're not using a pseudonym. @payingattention, can you confirm that it should be "Prosody Vereable Context(", or is it actually "Prosody Vereable Context" or "Prosody Vereable Context (Gabriel Gaston Croft)"? Apologies for the trouble, and thanks for contributing to the WHATWG!

Ideally, in order from first choice (0) to last choice (3) as follows, names listed in code quotes:

0) `prosody—Gab<!-- riel --> Vereable<!-- Gaston --> <!-- Croft -->Context(,` <<< from https://github.com/whatwg/dom/commit/6e33c904f01c39f6d6a1565757da383089cde382 (https://web.archive.org/web/20200719232739/https://github.com/whatwg/dom/commit/6e33c904f01c39f6d6a1565757da383089cde382)
1) `Prosody Vereable Context (Gabriel Gaston Croft)`
2) `Prosody Vereable Context("`
3) `Prosody Vereable Context`

Interestingly, Facebook.com has me registering "Gabriel Gaston Croft" as birth/former name and "Prosody Vereable Context" as current legal name (like Quora.com I mentioned before) so either search works to find/verify/vet me. The format my profile shows is "Prosody Vereable Context (Gabriel Gaston Croft)" for my FB.com public name setting.

![Screenshot from 2020-07-21 15-49-00 whatwg sg 101](https://user-images.githubusercontent.com/8619/88099978-f3c4ff80-cb69-11ea-863d-2d661bcca4c6.png) *Settings at https://www.facebook.com/prosody/about?section=bio*

![Screenshot from 2020-07-21 15-49-54 whatwg sg 101](https://user-images.githubusercontent.com/8619/88099990-f7f11d00-cb69-11ea-8cb3-852f88329e9f.png) *Main www.fb.com/prosody profile header.*

Note: I understand if the signature with <--comment--> style was not ideal (but I argue it shows the same for the user, and lets coders read details, like slugs work professionally with many hexspeak algorithms), The name comment code does not init or inject scripts, is only readable with "View Source...", but I will not fight if that's what causes an issue. I know it passed the security check, but we can change that, **I will defer (0) and (1) are okay.**

I will still be able to check the edit log for the name/identity version changes, and the/my original commit remains? https://github.com/whatwg/sg/issues/137 says keeps the info, but you're asking here so I am still nervous. How do I `"commit changes", or is the code stable? 

Can you replace mention of "the one person" https://github.com/whatwg/sg/issues/137 with my real name (and maybe my comment ID linked response before) please.

**Comment by foolip** [comment]
@payingattention I've sent https://github.com/whatwg/participant-data/pull/28 to update your name to "Prosody Vereable Context (Gabriel Gaston Croft)" to match your preference. I have also updated the meeting minutes in https://github.com/whatwg/sg/issues/137 as requested, which makes them clearer, thanks!

Thanks for your patience with this! There's no need to do anything else now, and no contributions (yours or any other) will be reverted. https://github.com/whatwg/sg/issues/138 tracks how we handle this better going forward.

**Comment by foolip** [comment]
https://github.com/whatwg/participant-data/pull/28 is merged now, so let's consider this issue resolved as per https://github.com/whatwg/sg/issues/101#issuecomment-661958660.
