### ISSUE TITLE
Figure out a good long-term solution for the Contributor and Workstream Participant Agreement

### ISSUE THREAD

**Issue by othermaciej** [whatwg/sg#13]
We're importing a copy of the CWA as agreement.hbs, but @domenic says:

> For at least now, the copy of agreement.hbs that's getting deployed to participate.whatwg.org will be the one from the https://github.com/whatwg/participate.whatwg.org repository. I'm not sure how to best handle that short-term. Long-term, we could have the whatwg/sg repository host that particular file if that's how the SG would prefer it.

We should figure out a good solution to this.

Ideally, we'd figure out a way where the text of the agreement could be owned by the SG, but the mechanics could all live in the participate.whatwg.org repo and be owned by Domenic and others working on it. I'm not sure of the best way to accomplish that.

**Comment by annevk** [comment]
https://github.com/whatwg/participate.whatwg.org/commits/master/views/agreement.hbs changed a few times and the SG has reviewed each time due to CODEOWNERS.

This repository still contains a dated copy of the same resource though. Shall we remove that and indicate in the README or some such that the SG is also responsible for the file in that other repository?
