### ISSUE TITLE
Signing the participation agreement as an individual

### ISSUE THREAD

**Issue by sideshowbarker** [whatwg/sg#62]
I’d like to sign the participation agreement as an individual but the *“I represent that I do not work in the field of web technologies as an employee, contractor, or agent of another person or legal entity”* language in the current agreement appears to prevent me from doing that.

I’m not authorized to sign an agreement like this on behalf of my employer as a whole. But anyway I’ve always participated in WHATWG work in a personal capacity and made my contributions in a personal capacity, and my contract with my employer doesn’t prevent me from agreeing on my own to any copyright grant on my contributions nor to royalty-free licensing of my contributions.

**Comment by michaelchampion** [comment]
@sideshowbarker who's your actual employer, Keio University? Or are you a contractor?  (W3C is not a legal entity, so I know you don't work for it).

**Comment by sideshowbarker** [comment]
Yeah, my employer is Keio University.

**Comment by othermaciej** [comment]
The WHATWG has discussed this, and we'd really like to figure out a way for W3C staff to participate. ?Nothing to announce yet but I wanted to say for the record that we have discussed it.

**Comment by chris-morgan** [comment]
The current ruling prevents many people such as myself from contributing. See some discussion in https://github.com/whatwg/html/pull/5156.

I am employed by a company that deals in web tech, but I attempted to contribute in my own time to correct an error I encountered while working on a project of my own, completely distinct from my employer. I cannot get my employer to sign the agreement and contribute the patch, because they hold no rights to the Contribution, and it is excessively onerous to set up some kind of copyright assignment or equivalent license grant of my own work to my employer so that I could submit the patch as an employee of that company. Yet I am not permitted to sign the agreement as an individual.

In short, catch-22, neither of the categories applies to me, and I am not permitted to contribute.

**Comment by sideshowbarker** [comment]
It’s worth noting here that at https://tc39.es/agreements/contributor/, in contrast to the WHATWG Participant Agreement, TC39 has a Contributor License Agreement form that explicitly allows a contributor to assert that they, individually, have the right to provide all contributions they are making — outside of whatever organization they may happen to be employed by. Specifically:

* The TC39 CLA has no language anything like the part of the WHATWG Participant Agreement that’d require TC39 individual contributors to assert that they don’t work “in the field of web technologies” or anything similar.
 
* the CLA form has this language:
    > I confirm that I have the right to provide all contributions I will make, and if I am making a contribution on behalf of an organization, I confirm that I have the right to make this contribution on behalf of my organization and to bind my organization to the obligations below

  So the CLA explicitly acknowledges and allows for the case where an contributor, even if employed by some organization (implicitly including employment “in the field of web technologies” or any other field), can assert  they as an individual *“have the right to provide all contributions I will make”* and are contributing individually and not on behalf of any organization. (That is, exactly the case @chris-morgan describes in https://github.com/whatwg/sg/issues/62#issuecomment-566384041 and that I’ve described for myself in the issue description here.)

--- 

Note also: the TC39 CLA further distinguishes between normative and non-normative changes, and signing the CLA at all is explicitly only required for contributors who are contributing normative changes; the top of the form says (emphasis added):

> It is required in the following cases:
> 
> * To attend a TC39 meeting as an invited expert and participate in committee discussion
> * **To contribute a normative change** to an ECMA-262, ECMA-402 or a proposal repository under the tc39 organization

**Comment by michaelcpuckett** [comment]
I am also an employed web developer who does not want to participate on behalf on my company. The W3C community group rules allow me to join as an individual if my employer has explicitly given me permission to do so, which they did. They were also willing to sign a document granting me permission, if needed.

My guess is that the vast majority of web developers are unable to participate under the current rules. This seems antithetical to the WHATWG's principles of openness, utility, efficiency and freedom.

I suggest this gets brought up again by the steering committee.

**Comment by michaelchampion** [comment]
I was on the Steering Group for 2 years, and I regret we didn't make more progress on this issue during my tenure.  I believe the SG is close to a resolution that should work for more individuals whose employers approve of them working in WHATWG but are unwilling to invest the legal resources needed to sign the  Entity Agreement.  But this is more complicated than it sounds:

- There's no clear way to distinguish between non-normative and normative changes in legal language.  There are (admittedly corner) cases where something as trivial as punctuation or capitalization can change the normative sense of some text.  Also, individuals can always suggest non-normative changes in Issues rather than Pull Requests without needing to make a formal patent commitment, so it's not clear how serious a problem this is for the community.

- The most compelling "threat models" for patent policies involve litigation by small players whose main asset is a patent, and non-practicing entities ("trolls") who acquire their patents if the business doesn't succeed.  What might seem like corner cases to engineers might be exploited by trolls and cost big companies implementing specs millions and millions of dollars. So attorneys are risk averse about patents even though few major companies use patents "offensively" in the web platform space anymore.

- Finally, the lawyers advising the SG companies work for each other's biggest competitors, so are extremely careful not to agree to a policy that could put one at a disadvantage compared to the others.  

That said, the WHATWG community should keep encouraging the SG to find a solution, and to keep pointing to other standards organizations that have solved this problem in a way big company attorneys can live with!

**Comment by annevk** [comment]
> Also, individuals can always suggest non-normative changes in Issues rather than Pull Requests without needing to make a formal patent commitment, so it's not clear how serious a problem this is for the community.

I think it's a serious problem, for what it's worth. We have people put effort into contributing a (pretty much always simple, without legal implications) fix only to belatedly realize it cannot be accepted because they cannot successfully navigate the Participation Agreement. This turns people away and they are unlikely to return after such an experience.

It's also somewhat absurd we have this high bar whereas for "equivalent" W3C efforts such changes are routinely merged.

**Comment by michaelchampion** [comment]
As a former SG member, I agree it's a problem that is turning people away.  The root of the issue is that if you ask a lawyer, almost nothing is "without legal implications." 

I suspect the SG would be interested in hearing from anyone who has PRs accepted in W3C land but has trouble navigating the participation agreement.  The idea was to allow anyone who can  make IPR commitments to W3C specs, either as a member or invited expert, to make equivalent commitments to WHATWG specs.

**Comment by foolip** [comment]
The SG discussed in https://github.com/whatwg/sg/issues/126, summarized as these two options:
- Case-by-case exceptions allowed for people employed by academic institutions (W3C does something similar for [invited experts](https://www.w3.org/participate/invited-experts/))
- Exception for all [W3C staff](https://www.w3.org/People)

Assigning to @travisleithead per the action item in those notes.

**Comment by chris-morgan** [comment]
So… no? Those options sound to me like they will solve the problem for very few people that are actually in this situation.

**Comment by dbaron** [comment]
I'd note that:
* they do address the situation that was the topic of the first four comments in this issue
* other situations may be addressed by the discussion in #63.

**Comment by othermaciej** [comment]
We have [landed changes](https://github.com/whatwg/sg/pull/129) that clarify what it means to "[work in the field of web technologies](https://whatwg.org/ipr-policy#210-field-of-web-technologies)". This should help some people who would like to join as an individual. In particular, being employed as a web developer is not enough, by itself, to count as "working in the field of web technologies".

We realize this doesn't cover everyone, but perhaps it will help some of those following this issue.

**Comment by annevk** [comment]
Now that we have an invitation policy this can be closed: https://blog.whatwg.org/update-from-the-steering-group.

**Comment by sideshowbarker** [comment]
Thanks to the SG and thanks individually to everybody involved in coming up with the invitation policy. I can imagine it must have taken a lot of work to get it through the necessary machinery, but I think the benefits from it are going to make it well worth the effort it took. This is a really big win for the community.
