### ISSUE TITLE
Announcing a Review Draft

### ISSUE THREAD

**Issue by annevk** [whatwg/sg#73]
https://whatwg.org/workstream-policy#announcing suggests to announce it in the repository. I guess this means as a new issue? Would we leave the issue open for 45 days and then close it if no escalation occurs?

I remember we also discussed notifying a set of people, but this isn't codified in our policies. @geoffcr had thoughts on that if I remember correctly. What kind of setup do we have for that ideally?

**Comment by annevk** [comment]
Alternatively, I suppose the pull request that adds the Review Draft could be considered the announcement. That won't stay open for 45 days however so that would make it less clear where to escalate.

**Comment by domenic** [comment]
> I remember we also discussed notifying a set of people, but this isn't codified in our policies. @geoffcr had thoughts on that if I remember correctly. What kind of setup do we have for that ideally?

Originally we had talked about creating a thing where you can sign up for notifications. However I talked further on this with our counsel and if I recall she suggested the issue would be sufficient. I should confirm.

An alternative is emailing everyone using the address they signed up to participate with, but especially for individual contributors that sounds pretty annoying. (Imagine every six months getting 15 unsolicited emails about patent exclusions that dribble in over a few days...)

**Comment by annevk** [comment]
Any kind of person-specific notification system would need to have opt-out/in to deal with that issue.

**Comment by domfarolino** [comment]
So the editors are supposed to do this every 6 months, but when does this start? Whenever? Could/will there be some notifying system to say "Hey Editor of XYX Standard, remember to publish a review draft soon"?

**Comment by annevk** [comment]
@domfarolino I suspect the SG, @domenic, and I will keep track for the foreseeable future, but I'm hoping #74 is reasonable to the SG so nobody will have to deal with this, unless there's an objection of sorts.

**Comment by geoffcr** [comment]
My sense is that three things would be useful here: 
(1) When a Review Draft is published, the notification is easy to spot among the other notifications one gets when Watching a repository. (ALL CAPS might suffice.)
(2) All of the primary and backup "Contacts" for a Workstream Participant should be "Watching" the Workstream repository - intially, anyway; if they don't care about patent reviews, they can Unwatch, but as a default, the person who is on point for a participant should get a notification from the repository when a Review Draft is published. 
(3) Since the exclusion opportunity is time-sensitive, the Review Draft should be time-stamped using UTC as the "zone".
Is that feasible? 
I'll forward this to my counterparts separately (I'm unable to tag them all here for some reason).

**Comment by annevk** [comment]
@geoffcr 3) was discussed in #70 and day was considered acceptable there. The tooling we have doesn't really provide for finer granularity either at this point. Perhaps counting could start from midnight UTC or some such?

**Comment by domenic** [comment]
(1) is easy enough; I think we could make the review draft issue have a prefix that people could filter for.

(2) is harder; we'd need to have people sign in with GitHub and give us permission to manipulate their repository-watching settings, which is fairly intrusive. (And we couldn't do it for two people at once, i.e. both the primary and backup contacts, since only one person would be signing the form and thus able to give us permission to access their GitHub account.)

My counter-proposal is that we put together some nice messaging on the "Thanks for signing up to participate" page that instructs you to please go watch the repositories you signed up for by following these links and clicking these buttons. And optionally, we could do a one-time email to everyone signed up so far (who didn't see that message because we hadn't made it up yet) explaining they might want to start watching too.

**Comment by geoffcr** [comment]
@annevk , I don't think the document itself needs a time-stamp, so long as there's a time-stamp associated with it. #70 indicates that there's a timestamp in git; I think that would suffice as a reference point. (All I'm looking for is that, if someone wants to exclude a patent, they can see that the Review Draft was posted at [time/date] and calculate whether they're within the 45 days (1,080 hours, 64,800 minutes) allowed for exclusions. So long as there's a single common time/date reference point, that addresses my concern.

**Comment by annevk** [comment]
Would "Review Draft May 2018" work as issue title? We can also label these issues to make them easier to find.

And if we can automate these we could even standardize on when they are published so everyone knows what day to pay attention. (Of course individual Review Drafts might get delayed a little, but the goal is that this is uncommon.)

**Comment by geoffcr** [comment]
For exclusions we need to start a 45-day clock. 

In my imagination, the Editor hits "Publish" and the Review Draft is stamped with UTC ... much the way email, messaging, and (I'm guessing) this Comment are tagged upon posting. 

Sounds as though that's harder than I had imagined.
("May 2018" might suffice for general-reference purposes, but it's not adequate as a formal reference point for exclusions.)

**Comment by annevk** [comment]
The issue is stamped with UTC so we could just use that. We could also use the timestamp of the commit on the master branch. It's just incorporated in the text of the draft itself.

**Comment by annevk** [comment]
Could also take the git master commit timestamp and mention that in the issue. There's still a bit of delay (minutes at most; unless there's problems with continuous integration) between that commit and the draft going live on the site though.

**Comment by othermaciej** [comment]
I think a day reference for exclusion is likely sufficient, as a period of 45 days is more reasonably treated as calendar days than 24-hour periods. (Of course, day still has to be relative to a time zone and the end of the 45th calendar day needs to be based on a specific time (midnight?) in a particular time zone. However, this should all be able to work without fine-grained date stamps. We have no need to quibble over seconds or minutes for an exclusion notice.)

**Comment by geoffcr** [comment]
That was the thought behind UTC: it's one zone for all. It can be Tuesday in New Zealand and Monday in Seattle, you can be on daylight savings time or not; the Review Draft gets posted at HH:mm on YYYY-MM-DD UTC and there are no issues about whether it's Tuesday or Monday or what.

**Comment by annevk** [comment]
https://github.com/whatwg/meta/blob/master/MAINTAINERS.md#review-drafts (at the bottom) are the instructions we have for editors thus far. Since issues have an accurate timestamp I suggest we use that, which means we can close this, unless anyone thinks the instructions need to be more explicit.

**Comment by domfarolino** [comment]
Agreed that this can be closed :)

**Comment by annevk** [comment]
Closing since we have announced them without issue.
