### ISSUE TITLE
Further Review Draft automation

### ISSUE THREAD

**Issue by annevk** [whatwg/sg#74]
Per https://whatwg.org/workstream-policy#review-drafts it seems that Review Drafts are published by the editor and then announced by the editor.

Is a bot acting on behalf of the editor acceptable here?

If it is, I think we could fully automate publishing Review Drafts every six months.

I think that's worthwhile as not doing it would mean quite a bit of manual work every six months, which will add up if we continue on for another decade plus (as we well should).

**Comment by othermaciej** [comment]
I personally think automation is acceptable. Nothing in the policy says there must be manual steps. 

That said, there is an expectation that the editor should be aware of and accountable for the contents of the Review Draft. Thus, I would like to see automation that has a few possible points of manual control:

1. Picks the target rev and makes a preview for the editor in advance, so the editor can look at it and make sure the rev and how it got processed is ok.
2. Lets the editor change the target rev and/or publication date if they want to (in case #1 reveals problems).
3. Lets the editor schedule an out-of-band review draft (for example, if we want to change timing for some external purpose).
4. It would be nice if there could be advance notice to the Workstream that a Review Draft is coming soon (not necessarily with a preview or specific revision) so participants can request "Objection Pending" or "Under Discussion" tags if they want to. Since those are the main way cause text to be excluded from the Review Draft, it would be good if there was a way to request them up front so we can avoid making a mechanism for updating a Review Draft in place.

It's ok if by default, if the editor takes no action, it spits out review draws exactly every 6 months made from arbitrary revisions.

**Comment by henceproved** [comment]
All of us on the SG agree that automation is totally acceptable and that we should explore it. Leaving this issue open for tracking purposes, but assuming no further action needed from the SG at this time.

**Comment by othermaciej** [comment]
Closing this issue, since a decision was made, and there hasn't been further discussion in this form of how to add more automation.

**Comment by annevk** [comment]
FYI, the one thing I'm planning on doing when we get to the next round is write a small script you can run locally that puts up the necessary PRs. The PRs will still be reviewed, landed, and have a comment added manually though if https://cli.github.com/ allows for it by then we could automate that too as a script for someone else to run.
