### ISSUE TITLE
Is Wikimedia Foundation in the field of web technologies?

### ISSUE THREAD

**Issue by annevk** [whatwg/sg#84]
https://github.com/whatwg/dom/pull/675 is a contribution by @cscott who signed up as an individual. @domenic discussed this with me and neither of us is quite sure whether Wikimedia has to sign up as an entity for its employees to contribute.

@cscott apologies for the delay in merging your PR this inquiry will likely cause.

**Comment by ediosyncratic** [comment]
The very fact that you're struggling with the question says that the formulation "in the field of web technologies" is broken.  The relevant rule should be phrased in terms of: does your contract of employment potentially cover your contribution ?  If it has a provision for your employer to waive its potential interest in this contribution, have you obtained such a waiver ?  If so, no problem.  The only problem arises if my contract of employment gives my employer control (that they haven't waived) over my contributions to this work.

If you're worried that my contribution might be slipping some patent-dependent acid into your water supply, then you have to worry that I'll get some friend (who works in a field that's not web-related) to submit it and you'll *still* be spiked on my patent, so the "in the field of web technologies" employment test doesn't protect you.  Separate question then: do you know of any party that may have an interest in a patent that might cover your contribution, or implementations of our standard as amended by your contribution ?

Meanwhile, @annevk: many old Opera-ites are about to gather hos Vivaldi to meet Lissie, who's visiting from the antipode :-)

**Comment by cscott** [comment]
@ediosyncratic I'm a little puzzled by your comment here.  Perhaps when you write "my contribution" you really means something like "someone's contribution might be slipping", since it is @cscott's contribution which is being discussed not @ediosyncratic's.

In the present case I'm pretty sure that my contribution in https://github.com/whatwg/dom/pull/675 would be considered de minimis, but I understand that the approval process is intended to be "once for all" so if I later go and contribute something more substantial it would be covered by the same waiver.

**Comment by cscott** [comment]
If it helps, I consider my contributions to standards bodies as personal work, and github.com/cscott is my personal github account.  There is a github.com/wikimedia org account, and I could do a PR from there if my contribution was supposed to be attributed as an official work product.  Since the contribution agreements seem to be tied to specific github accounts, it seems like it would be a mistake to accredit @cscott as wikimedia, since my employment status is mutable.

I don't expect there would be any problem in having wikimedia release copyright or other interest in the contribution (there is a clause in my contract already mandating that all of my for-work contributions must be distributed by WMF under an open source or creative commons license), but the rules for "entities [in the field of web technologies]" are stricter:

>Each Entity must:
>* identify a single person to serve as primary contact with the Steering Group,
>* identify individuals who are authorized to participate in each Workstream, and
>* notify the Steering Group if an individual’s authorization to Contribute is terminated.

That seems like quite a lot of overhead, and the fact that it doesn't really make sense for Wikimedia to do this confirms to me that Wikimedia must not be "in the field of web technologies" as used here.  We use web technologies, but we don't make browsers.  We create web content, but we don't consume or index it.  I can't individual any individual employee at the foundation who it would make sense to name as a "primary contact with the Steering Group".

Put another way, just because I publish a personal blog on my web page using HTML doesn't make me a "in the field of web technologies".  Similarly, the fact that Wikipedia is published in HTML (and uses HTML as an intermediate content representation in some places) doesn't make it "in the field of web technologies".

**Comment by dwsinger** [comment]
I think we should err on the side of yes. We are asking for only a patent commitment. If they think or know they don’t have any, then they will sign as it costs nothing. If they resist, that may be a reason to be more cautious

**Comment by cscott** [comment]
As I wrote, it is not the copyright or patent commitment I expect to cause problems. I have an open source clause in my contract which would apply if this were a contribution as a Wikimedia Foundation (WMF) employee.  It is the other organizational requirements imposed on an "Entity", portions which I quoted above.  WMF don't have anyone in a "liason with standards body" role AFAIK.  The "entity" requirement is an on-going commitment in the foundation, which is different from simply approving a one-off contribution.

(And appointing a formal liason to the WHATWG seems overkill for a patch which removes only two normative words from the spec, but...)

Could someone point me at a more precise definition of "in the field of web technologies"? I suspect I could produce a statement from WMF legal that we are not "in the field of web technologies" if that would help (and it could be defined).

Also: "It costs nothing" might be the lowest hourly rate I have ever heard quoted for legal work.

It would be helpful to me if participants here identified their formal relationship to this process, so I know who is stating binding legal opinion vs stating their own informal thoughts.

**Comment by othermaciej** [comment]
Per the Participant agreement, what really matters is whether the individual making a contribution is employed to work in "the field of web technologies". You can't necessarily just look at the company. Someone employed by Wikimedia Foundation to administer their well-known collaborative educational sites is not employed in the field of web technologies, in my opinion. Someone employed to work on the MediaWiki software likely is (though I'd probably get legal advice on their drafting intent).

**Comment by ediosyncratic** [comment]
@cscott - sorry I was unclear - I was thinking of the clauses in question, in their general intent and purpose, and of the contributions they relate to in general, not any particular contribution.  (As it happens, I've been through exactly this discussion most of a year back for exactly the same reasons over a similarly _de minimis_ contribution.)  The policy demands "Entity" membership where it makes no sense to do so.  If my employer might have a claim on the actual contribution, as they do have a claim over any work I do that relates to my job unless they explicitly waive that claim, then it would be necessary either for them to be an "Entity" member or for them to waive any claim to the contribution at hand; but the latter would suffice (and the Open Source clause in your contract sounds a lot like it achieves that by default - but IANAL, etc.).  In the case of our trivial contributions, I'm fairly sure no court would accept that they constitute a basis for any claim of copyright in the result; fixing grammar and punctuation is firmly below the threshold of anything that can be called "creative", which is a prerequisite of the relevant (patent and copyright) laws.

The idea that the Entity rule in any way protects against patent problems is entirely wrong-headed: no matter what my employer's field of work, no matter how one defines "in the field of web technology" or whether it fits them, a contribution I make might nudge the standard towards obliging implementors to step on a patent, that I may or may not know about,  A "non-practicing entity" that files patents on anything it can think of (without doing anything useful, lest they step on someone else's patent) might perfectly well declare itself to not be "in the field of web technology" - it's in the field of "legal services" - yet it is far more of a threat to the standard than any business actually in the field of web technology. The best that can be said for the Entity rule is that WHATWG needs everyone that could have a patent bearing on web standards to be a member; most of the folk who can usefully contribute to its standards are employed in some way not entirely unrelated to web technologies; and refusing contributions from those competent to deliver them is a way to pressure some businesses (who probably aren't the main patent threat, since it's not actually in their interests to cripple the web) into signing up.  A clumsy and misguided way, that works on all the wrong businesses and won't at all affect the patent trolls, but hey.

As to whether WMF is in the field of web technology, I would have to say that it indisputably is.  It produces a technology (WikiMedia) which is used to implement web-sites.  If a court had to decide the question and either side claimed WMF was in the field, that side would only need to explain - honestly, straightforwardly and without any effort to distort or mislead - what WikiMedia **is** for it to be impossible for the court to decide other than that yes, indeed, that is a web technology, plain and simple.  The fact that you, personally, don't work on that web technology is unlikely to matter.  The intent of the authors of the Entity policy would only come into play if there was any ambiguity in the question; and I doubt a court would accept that this applies.  If the authors of a contract phrase it badly, they're stuck with that phrasing, although the two parties might well follow a common intent at odds with the contract and have no problem as long as they never end up in a dispute; but then it would be better for them to re-write the contract in such a case (or to tear up the contract and admit they're capable of working together on mutually agreeable terms anyway).  But IANAL and yadda.

**Comment by annevk** [comment]
@othermaciej can the SG get such council and some to a decision? This is currently blocking a rather trivial PR against the DOM Standard that would be good to land.

**Comment by annevk** [comment]
It would also help if the SG could clarify this in general, perhaps as part of #65 or #67.

**Comment by sideshowbarker** [comment]
> Per the Participant agreement, what really matters is whether the individual making a contribution is employed to work in "the field of web technologies". You can't necessarily just look at the company. Someone employed by Wikimedia Foundation to administer their well-known collaborative educational sites is not employed in the field of web technologies, in my opinion. Someone employed to work on the MediaWiki software likely is (though I'd probably get legal advice on their drafting intent).

By that logic, then, I guess that language also doesn’t apply to me or any other W3C staff either.

**Comment by sideshowbarker** [comment]
> We are asking for only a patent commitment. If they think or know they don’t have any, then they will sign as it costs nothing. If they resist, that may be a reason to be more cautious

The Participant Agreement isn’t only asking for a patent agreement. It rightly *should* only be asking for that, but it’s not. If it were asking only for a patent commitment, I’d be able to sign it, and @ediosyncratic would be able to, and it seems like @cscott would be able to — because none of has any patents and none of us have an employment contract that would give our employers control over any aspect of our contributions to WHATWG work.

That problem isn’t that we’re “resisting” — the problem is instead that we *can’t* sign the curent Participant Agreement as individuals, because the language of the agreement states:

> I represent that I do not work in the field of web technologies as an employee, contractor, or agent of another person or legal entity

In the specific case under discussion in this issue, it seems that @cscott does pretty clearly does “work in the field of web technologies” and is an employee of the Wikimedia Foundation, and so by the current language of the agreement is left without the option of signing the Participant Agreement as an individual.

Other potential contributors are going to continue to run into this same roadblock unless the language of the Participant Agreement for individuals is changed.

**Comment by cscott** [comment]
Just for the record, I don't necessarily agree that the Wikimedia Foundation is in "the field of web technologies" -- as I understand it, the intent is to encompass browser makers, extension vendors, and those who might reasonably have a vested interest in influencing web standards work.  But it is obvious there's a lot of confusion about what exactly "the field of web technologies" is.  Presumably the definition is not intended to apply to every company with a web site.  But perhaps it is intended to apply to every company which distributes software with an internet API?  Surely it doesn't apply to every company whose internal software *uses* an internet API?

**Comment by ediosyncratic** [comment]
@cscott The intent of the drafters is irrelevant unless a court has doubts about its application to the case in hand.  If the agreement wants "works in the field of web technologies" to mean something specific, it needs to say so explicitly.  It doesn't.  If the only language it has to look at asks about what work **you** do, then you're probably safe; but your colleagues who implement WikiMedia - a software package used to implement web-sites - are unequivocally implementing a "web technology".  If the WhatWG folk don't intend their phrase to include that, where the vernacular surely does, the agreement needs to be explicit and say what it means.  That's what the "Definitions" section in agreements is for.

@sideshowbarker My contract does actually have fairly broad language in it about my employer having control over anything I do that "relates to my work" - again, horribly broad language - but I can get exemptions in a fairly routine way (so, for example, a project I have here on github is exempt).  I'm confident no court would accept that a typo fix for the WhatWG "relates to my work", so that's safe anyway (and I'm confident I would have got an exemption without trouble).  In any case, such _de minimis_ contributions are incapable of dragging any copyright or patent claim in, so it would be absurd to require my employer to sign the agreement in order to let me make such a contribution (frankly, it's absurd to ask _me_ to do so, for such trivia).

@dwsinger "only asking for a patent commitment" may seem trivial to you, but asking a contributor to get their employer to agree to **anything** means asking them to persuade managers who don't understand law or what WhatWG is to talk to lawyers whose time is expensive about something that doesn't gain their business anything.  Corporate suits don't spend lawyer time on entering into agreements unless they can see how that affects their bottom line.  So, even if they have no patents, they're allergic to committing to not do something that looks, on paper, like it might improve the bottom line, if they ever had the chance to do it.  (I remember BT holding the whole web to ransom over the hypertext idea, until Vannevar Bush's prior art stomped that idiocy, and someone else forcing browser vendors to make plugins harder to use for similar motives.  Corporate suits have wet dreams about this stuff, the rest of us have nightmares; fortunately, they're seldom actually realisable.)

Meanwhile, it's a wanton imposition on a humble minion of those corporate suits to demand even a personal sign-up when the contribution - fixing typos or grammar - is below the threshold of containing any "expressive" or "creative" element, so incapable of being the basis of any copyright or patent claim by anyone.  WhatWG's policies should distinguish **substantive** contributions (which do need some form of sign-up) from trivia; and (back to the topic in hand), for substantive contributions, to address the question of whether the contributor's employer **actually** has any way to make claims over (or arising from) the contribution: only then is a corporate sign-up really necessary.

**Comment by henceproved** [comment]
@cscott The SG is considering this issue and we will, at the least, work on a detailed FAQ that would clarify the language and help make quicker decisions in such situations. We are getting legal counsel and will report back on this, as soon as possible. Apologies on the delay, we really don't like blocking any PRs for these reasons.

**Comment by sjamaan** [comment]
I also have a PR that requires me to fill in the participation agreement. I work for a company which makes b2b web applications, and some lower-level tools like a REST framework built on Django, a websocket broker and so on. My PR is https://github.com/whatwg/url/pull/416. This is work I'm doing in my personal free time, though (otherwise, like @cscott says, I would have made the PR from the @CodeYellowBV account.

**Comment by cscott** [comment]
It has been six months now, and the PR is still blocked.  Did the SG come to any conclusion?

**Comment by cscott** [comment]
As of this week(ish), the Wikimedia Foundation is a member of the W3C.  Does that make this issue simpler?

**Comment by henceproved** [comment]
Perhaps. It does seem clearer to me that Wikimedia Foundation works in the field of web technologies. Have you recently discussed with your employer about signing the WHATWG agreement as an entity? Are there concerns they have with signing as an entity that we can help answer/mitigate?

Also, our legal advisors have shifted focus back to this question since last couple weeks and are actively working on a more detailed definition/FAQ that would help us move more swiftly on such questions in the future.

**Comment by domenic** [comment]
Somewhat, in that if your lawyers were OK joining the W3C, they should have a much easier time signing the WHATWG participation agreement as an entity.

**Comment by cscott** [comment]
No worries.  The issue was never whether WMF would be willing, it was whether they'd be *required* to. Remember the context was contributions from my personal github account as a volunteer.

I'm glad to hear from @henceproved that there will be more clarity to come.

**Comment by henceproved** [comment]
Even if it is from your personal github account, your employer's field (whether they are in the field of web technologies), as well as your role in the company does matter. The key phrase here is "working in the field of web technologies", so it's a combination of your role plus your employer's field. At this point, if WMF is willing to sign as an entity, that definitely seems like the reasonable path forward. I would find it much harder to argue that WMF is not in "the field of web technologies", if they are participating in and influencing web standards. If your role in WMF is not related to web technologies AT ALL, we may still have a case, but it gets considerably blurrier from that point forward.

**Comment by cscott** [comment]
At the time I submitted the patch and historically, WMF has definitely not seen itself in "the field of web technologies" and was not a member of any standards bodies.  Its joining the W3C was a break from the past. And as evidenced by the other comments on this thread, there are others who are employed by companies which have a web presence (doesn't every piece of software have a web component these days?) but which do not consider themselves "in the field of web technologies".  Clarification will be a step forward, regardless of whether it eventually helps me personally.

**Comment by henceproved** [comment]
You are absolutely right, that would be a step forward! Everybody on the SG, and I believe on this thread, agrees that the definition can use clarification, so no arguments there. That work is ongoing, irrespective of any decision on this issue; it's frustrating how long we are taking to answer your question definitively.

What would you like to do about your specific case? Would you like to wait till we have that definition, and based on that, try to advocate that your situation does not require WMF signing as an entity, or would you like to discuss with your employer if they would like to sign as an entity?

**Comment by cscott** [comment]
I've started the conversation at WMF about WHATWG.  I'm happy to wait and see for now (it's been 9 months, what's a few more weeks), and we'll see whether WMF or WHATWG manage to reach a decision first. ;)

**Comment by othermaciej** [comment]
The new definition of [working in the field of web technologies](https://whatwg.org/ipr-policy#210-field-of-web-technologies) makes clear that it's the individual's role that is relevant, not the company's line of business. And the individuals role is in the field of web technologies if they are "creating and influencing web standards and web technologies that could be adopted by the web community" as part of their job.

Since this issue doesn't explain the individual's role, we can't determine if individual agreement would be ok. Please provide that info and we'll help make the call.

**Comment by annevk** [comment]
Closing this due to lack of follow-up and because field of web technologies has been clarified as stated above. As this was originally raised for a rather small change, I created a PR for it myself at https://github.com/whatwg/dom/pull/945.
