### ISSUE TITLE
Is Salesforce.com in the field of web technologies?

### ISSUE THREAD

**Issue by annevk** [whatwg/sg#85]
It's a very trivial PR (see https://github.com/whatwg/dom/pull/681), but as #63 is not resolved yet, I guess I better ask.

@pmdartus if Salesforce.com has no problem joining the WHATWG as entity they can go ahead, you can make your contribution on their behalf, and this will go away, but otherwise I'm afraid I have to wait with merging your PR until the Steering Group resolves this question. Sorry. 😟

**Comment by pmdartus** [comment]
@jamesward, do you see any concern with Salesforce.com joining WHATWG?

FYI @caridy

**Comment by annevk** [comment]
To be clear, the Participant Agreement can be found at https://participate.whatwg.org/agreement.

**Comment by jamesward** [comment]
We will just have to work with our legal team on getting those agreements signed.

**Comment by ediosyncratic** [comment]
@othermaciej your phrasing "... particularly if it's feasible to get Salesforce.com to join as an entity." leads me to ask: what is the actual intent of this clause in your T&C ?  Specifically, is it to protect WhatWG and implementors of its standards from legal hassles ?  Or is it part of a recruitment drive to get as many businesses as possible to sign up as corporate members of WhatWG, by putting their technical staff in the annoying position of not being able to contribute improvements until they twist their bosses arms ?

If it's the latter, please understand that some of us, that could make useful technical contributions, will simply walk away.  I might send @annevk an e-mail about any suggestions I have, or file a bug-report, but I'd simply refuse to be used as a pawn in your recruitment strategy.  Unless and until I make a contribution in which my employer has some plausible business interest, I am not interested in even asking them to consider signing up to WhatWG, nor would I be even if their business was "in the field of web technologies" (which is debatable either way, as it happens - Qt does include implementations of HTTP and Web Sockets, after all; and I routinely review changes other developers make to that code).  Had that meant I couldn't fix a typo, I'd just have reported it (on github, as an issue) and refused to waste my time turning it into a pull request.  (I will note that, when I reported a typo fix, that was trivial, I was surprised that someone asked me to turn it into a pull request; but obliged; and was thus somewhat irritated to have to deal with the whole sign-up thing, which seemed very low-value *to me*, but I put up with it, only to end up getting dragged into the tricky question of whether I work "in the field of web technologies".)

If the actual intent of the language is to protect WhatWG and impelmentors of its standards from legal hassles of various kinds, then the language should be changed to not require even personal sign-up for changes that don't rise to the level of having any "expressive" or "creative" substance (e.g. typo fixes, grammar tidying), since there's no plausible attack model via making such contributions, and to accept personal sign-up unless the contributor's employment comes under a contract that can make claims, that their employer hasn't waived, over free-time contributions such as they're making.  Requiring more than that is an annoyance that'll put off some contributors and annoy those close to the boundary of whatever standard you do impose for sign-up, if that boundary isn't placed close to where it's actually needed.

Chose one, don't mix them up: make up your mind and be honest about which you've chosen.

**Comment by michaelchampion** [comment]
> If the actual intent of the language is to protect WhatWG and impelmentors of its standards from legal hassles of various kinds, 

That is the actual intent of the language.  WHATWG doesn't collect dues or really have a concept of "membership" beyond "people who are capable of improving web standards and willing to make a binding commitment to not enforce any patents on the improvements they contribute."   That said, it would be great to get big companies who have a potential impact on web technology standards to sign on to WHATWG as "entities" to make it easier for more experienced engineers to fully participate.

> then the language should be changed to not require even personal sign-up for changes that don't rise to the level of having any "expressive" or "creative" substance (e.g. typo fixes, grammar tidying), since there's no plausible attack model via making such contributions

Unfortunately, and I speak for long experience dealing with big-company lawyers on standards matters, what sensible laypeople think of as a "plausible attack model" is not the way attorneys view the world.  They're looking for small loopholes to close in agreements or exploit in litigation.  Likewise, they're not thinking about the vast majority of good people just trying to help, they're worried about the occasional bad actor.  I know it's frustrating, and the Steering Group can keep evolving the legal documents to find a better balance between worst-case scenarios and day to day reality. 

A @othermaciej says "Currently, the IPR Policy has no exception for trivial changes. It's something we are considering, but no changes have happened as yet."  We ask for patience while we learn what parts of the IPR policy created less than a year ago are lawyer-speak trying to make the world simpler and clearer than it really is, and which are fundamental to our mission. But it's not easy to define what non-substantive changes are, and IIRC from previous discussions with attorneys on the topic, there are precedents for apparently trivial changes being exploited in patent litigation. 

If it is possible to just work with your attorneys and managers to get the legal agreements signed, that would be the best way forward.  If Salesforce attorneys have concerns about the text, we can probably arrange for them to talk to the attorneys who advise the Steering Group to clarify or even suggest improvements.

**Comment by annevk** [comment]
@ediosyncratic I'd appreciate it if we could keep this thread focused on Salesforce.com. #63 and #67 cover the overarching problem here, that I think is acknowledged by having those issues and keeping them open. If there is more to say publicly, please contribute that there. Thanks!

**Comment by othermaciej** [comment]
@ediosyncratic as @michaelchampion says, the intent of the IPR Policy is entirely to protect implementors, as well as anyone reusing the text, from legal hassles. Our goal is to ensure that implementing or using the standard [remains royalty-free](https://whatwg.org/principles#freedom). Thus, we ask for patent on copyright grants for contributions, and we seek broad patent commitments on the full contents of Living Standards from as many organizations as possible. We believe it is critical to the health of the web to uphold royalty-free licensing.

It is tough to balance this against making it reasonable to contribute. We are still considering revisions. As @michaelchampion says, abusive organizations have found all kinds of tricks for evading IPR policies. And trying to block those attack modes unfortunately also catches some legitimate and innocent behavior.

Our desire to have organizations join is absolutely not for any kind of PR reason. We have never used the organizations that have signed the Entity agreement for promotional reasons and have no intention to do so.

(Posting here because it was a direct question and I believe the rationale for the policy is also relevant to Salesforce.com's decision to join.)

**Comment by pmdartus** [comment]
@annevk This issue can be closed. Salesforce has finally [signed the aggrement](https://github.com/whatwg/participant-data/commit/c1f9b1775ecbe2924da01520dbfb00b9685a74bc) (after more than a year :tada:).
